setup = 'a duck goes into a house...'

print(setup.strip('.'))   # a duck goes into a house
print(setup.capitalize()) # A duck goes into a house...
print(setup.title())      # A Duck Goes Into A House...
print(setup.upper())      # A DUCK GOES INTO A HOUSE...
print(setup.lower())      # a duck goes into a house...
print(setup.swapcase())   # A DUCK GOES INTO A HOUSE...
print(setup.center(30))   #  a duck goes into a house...
print(setup.ljust(30))    # a duck goes into a house...
print(setup.rjust(30))    #    a duck goes into a house...

print(setup.replace('duck', 'marmoset'))   # a marmoset goes into a house...
print(setup.replace('a', 'a famous', 100)) # a famous duck goes into a famous house...

