outf = open('LogoSong.txt', 'w')
outf.write('하나님의 도를 따르는 사람들\n')
outf.write('여기 모였네 두손들고\n')
outf.write('그분의 이끄심을 체험하는\n')
outf.write('한동대학교\n')
outf.close()
inf = open('LogoSong.txt', 'r')
s = inf.readlines()
print(s)
inf.close()